services:
  app:      # app 이하 코드를 도커 이미지 빌드 후 추가!
    image: backend-app:local
    container_name: backend-app-dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - backend-mysql
    restart: unless-stopped

  # 여기부터 원래 있던 코드
  backend-mysql:
    image: mysql:8.0.43
    container_name: backend-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: backend_root
      MYSQL_DATABASE: backend_db
      MYSQL_USER: backend_user
      MYSQL_PASSWORD: backend_pw
      TZ: Asia/Seoul
    command: [
      "--default-authentication-plugin=caching_sha2_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    ports:
      - "3306:3306"
    volumes:
      - ./_vol/mysql:/var/lib/mysql